title: Adam's Internet
description: A personal website.
baseurl: ""
theme: just-the-docs
url: https://adamloec.github.io

permalink: pretty

color_scheme: dark

search_enabled: false

enable_copy_code_button: true
