title: Adam's Internet
description: A personal website.
baseurl: ""
theme: just-the-docs
url: https://adamloec.github.io

permalink: pretty

color_scheme: nil # nil/light/dark

search_enabled: false

enable_copy_code_button: true

callouts:
  note:
    title: NOTE 
    color: blue
  header:
    color: blue

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false